version: 2.1
jobs:
  build:
    docker:
      - image: jguyomard/hugo-builder
    steps:
      - checkout

      - run:
          name: build
          command: |
            hugo -d /tmp/output
            git checkout master
            rm -rf *
            mv /tmp/output/* .

      - when:
          condition: $CIRCLE_BRANCH == "docs"
          name: deploy
          command: |
            echo "test"
