version: 2.1
jobs:
  build:
    docker:
      - image: jguyomard/hugo-builder
    steps:
      - checkout

      - run:
          name: build
          command: |
            hugo -d /tmp/output
            git checkout master
            rm -rf *
            mv /tmp/output/* .

      - run:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "ci" ]; then
              git config user.name "CircleCI Bot"
              git config user.email "circleci@circleci"
              git add --all
              git commit -m "automated build"
              git push -u origin/deploy
            fi
